development:
  adapter: async

test:
  adapter: async

production:
  adapter: postgresql
  url: postgres://mndqzvryvwtzsk:988652754ad42f5f4f0bcb9cc68ff34b6ee8e63f45b79f08029c4f32f0c180a7@ec2-23-21-169-238.compute-1.amazonaws.com:5432/dbe4h2vqab0rds
